# Bangalore House Price Prediction

ML Model developed

In [9]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

In [11]:
# get clean data 
path = r"ohe_data_reduce_cat_class.csv"
df = pd.read_csv(path)
df.shape

(7120, 108)

In [12]:
df.head()

bath  balcony  price  total_sqft_int  BHK  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area   area_typeBuilt-up  Area  \
0                               0                        0   
1                               0                        1   
2                               0                        0   
3                               0                        0   
4                               0                        0   

   area_typePlot  Area    availability_Ready To move   locationWhitefield  \
0                      0                            0                   0   
1                      0                            0                   0   
2                      0                            0                   0   
3                      0                            0                   0   
4                      0                            0                   0   

   locationSarjapur  Road  locationElectronic City  locationMarathahalli  \
0                       0                        0                     0   
1                       0                        0                     0   
2                       0                        0                     0   
3                       0                        0                     0   
4                       0                        0                     0   

   locationRaja Rajeshwari Nagar  locationHaralur Road  locationHennur Road  \
0                              0                     0                    0   
1                              0                     0                    0   
2                              0                     0                    0   
3                              0                     0                    0   
4                              0                     0                    0   

   locationBannerghatta Road  locationUttarahalli  locationThanisandra  \
0                          0                    0                    0   
1                          0                    0                    0   
2                          0                    0                    0   
3                          0                    0                    0   
4                          0                    0                    0   

   locationElectronic City Phase II  locationHebbal  locationYelahanka  \
0                                 0               0                  0   
1                                 0               0                  0   
2                                 0               0                  0   
3                                 0               0                  0   
4                                 0               0                  0   

   location7th Phase JP Nagar  locationKanakpura Road  locationKR Puram  \
0                           0                       0                 0   
1                           0                       0                 0   
2                           0                       0                 0   
3                           0                       0                 0   
4                           0                       0                 0   

   locationSarjapur  locationRajaji Nagar  locationBellandur  \
0                 0                     0                  0   
1                 0                     0                  0   
2                 0                     0                  0   
3                 0                     0                  0   
4                 0                     0                  0   

   locationKasavanhalli  locationBegur Road  locationBanashankari  \
0                     0                   0            

# Split Dataset in train and test 

In [13]:
X = df.drop("price",axis=1)
y = df['price']
print('Shape of x = ' , X.shape)
print('Shape of y= ', y.shape)

Shape of x =  (7120, 107)
Shape of y=  (7120,)


In [14]:
from sklearn.model_selection import train_test_split
x_train , x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=51)
print('Shape of x_train =', x_train.shape)
print('Shape of x_test =', x_test.shape)
print('Shape of y_train =', y_train.shape)
print('Shape of y_test =', x_test.shape)

Shape of x_train = (5696, 107)
Shape of x_test = (1424, 107)
Shape of y_train = (5696,)
Shape of y_test = (1424, 107)


# Feature Scaling 

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

# Machine Learning Model Training 

# Linear Regression

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
lr = LinearRegression()
lr_lasso = Lasso()
lr_ridge = Ridge()

In [17]:
def rmse(y_test,y_pred):
    return np.sqrt(mean_squared_error(y_test,y_pred))

In [18]:
lr.fit(x_train,y_train)
lr_score = lr.score(x_test , y_test)
lr_rmse = rmse(y_test,lr.predict(x_test))
lr_score , lr_rmse

(0.7917597629438351, np.float64(64.68506741226294))

In [19]:
# lasso 
lr_lasso.fit(x_train,y_train)
lr_lasso_score = lr_lasso.score(x_test , y_test)
lr_lasso_rmse = rmse(y_test,lr.predict(x_test))
lr_lasso_score , lr_lasso_rmse

(0.8038888209188495, np.float64(64.68506741226294))

# Support Vector Machine 

In [20]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(x_train,y_train)
svr_score = svr.score(x_test , y_test)
svr_rmse = rmse(y_test,svr.predict(x_test))
svr_score , svr_rmse    ## svm give bad accuracy

(0.21652033424588024, np.float64(125.46875107934606))

# Random Forest Regressor

In [21]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(x_train,y_train)
rfr_score = rfr.score(x_test , y_test)
rfr_rmse = rmse(y_test,rfr.predict(x_test))
rfr_score , rfr_rmse 

(0.8889331345436483, np.float64(47.240443698719))

# XGBoost

In [22]:
import xgboost
xgb_reg = xgboost.XGBRegressor()
xgb_reg.fit(x_train,y_train)
xgb_reg_score = xgb_reg.score(x_test , y_test)
xgb_reg_rmse = rmse(y_test,xgb_reg.predict(x_test))
xgb_reg_score , xgb_reg_rmse

(0.8860465916025513, np.float64(47.85037770035778))

In [23]:
print(pd.DataFrame([{'Model':'LinearRegression','Score':lr_score,'RMSE':lr_rmse},
                    {'Model':'Lasso','Score':lr_lasso_score,'RMSE':lr_lasso_rmse},
                    {'Model':'Support vector Machine','Score':svr_score,'RMSE':svr_rmse},
                    {'Model':'Random Forest','Score':rfr_score,'RMSE':rfr_rmse},
                    {'Model':'XGBoost','Score':xgb_reg_score,'RMSE':xgb_reg_rmse}],
                    columns=['Model','score','Rmse']))

                    Model  score  Rmse
0        LinearRegression    NaN   NaN
1                   Lasso    NaN   NaN
2  Support vector Machine    NaN   NaN
3           Random Forest    NaN   NaN
4                 XGBoost    NaN   NaN


# Cross Validation

In [24]:
from sklearn.model_selection import KFold,cross_val_score
cvs = cross_val_score(xgb_reg,x_train,y_train,cv=10)
cvs , cvs.mean()  

(array([0.98723741, 0.9821545 , 0.97920817, 0.98822994, 0.96081507,
        0.98620861, 0.97614513, 0.85294769, 0.9900092 , 0.89537911]),
 np.float64(0.9598334846987727))

In [25]:
cvs_rfr2 = cross_val_score(RandomForestRegressor(),x_train,y_train,cv=10)
cvs_rfr2,cvs_rfr2.mean()

(array([0.99502364, 0.94509698, 0.99743792, 0.96889557, 0.96468654,
        0.9503568 , 0.93243777, 0.91328776, 0.99638454, 0.98342702]),
 np.float64(0.964703453661836))

# hyper parameter Tuning 

In [26]:
from sklearn.model_selection import GridSearchCV
from xgboost.sklearn import XGBRegressor

# verious hyper- prameter to tune 
xgb1 = XGBRegressor()
parameters = {'learning_rate': [0.1,0.03, 0.05, 0.07], #so called `eta` value, # [default=0.3] Analogous to learning rate in GBM
              'min_child_weight': [1,3,5], #[default=1] Defines the minimum sum of weights of all observations required in a child.
              'max_depth': [4, 6, 8], #[default=6] The maximum depth of a tree,
              'gamma':[0,0.1,0.001,0.2], #Gamma specifies the minimum loss reduction required to make a split.
              'subsample': [0.7,1,1.5], #Denotes the fraction of observations to be randomly samples for each tree.
              'colsample_bytree': [0.7,1,1.5], #Denotes the fraction of columns to be randomly samples for each tree.
              'objective':['reg:linear'], #This defines the loss function to be minimized.
 
              'n_estimators': [100,300,500]}
 
xgb_grid = GridSearchCV(xgb1,
                        parameters,
                        cv = 2,
                        n_jobs = -1,
                        verbose=True)
 
xgb_grid.fit(x_train, y_train)
print(xgb_grid.best_score_)
print(xgb_grid.best_params_)
 

Fitting 2 folds for each of 3888 candidates, totalling 7776 fits


/Users/ankushchoudhari76/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [13:17:34] WARNING: /Users/runner/work/xgboost/xgboost/src/objective/regression_obj.cu:227: reg:linear is now deprecated in favor of reg:squarederror.
  warnings.warn(smsg, UserWarning)
/Users/ankushchoudhari76/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [13:17:34] WARNING: /Users/runner/work/xgboost/xgboost/src/objective/regression_obj.cu:227: reg:linear is now deprecated in favor of reg:squarederror.
  warnings.warn(smsg, UserWarning)
/Users/ankushchoudhari76/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [13:17:35] WARNING: /Users/runner/work/xgboost/xgboost/src/objective/regression_obj.cu:227: reg:linear is now deprecated in favor of reg:squarederror.
  warnings.warn(smsg, UserWarning)
/Users/ankushchoudhari76/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [13:17:35] WARNING: /Users/run

0.9389357649860018
{'colsample_bytree': 1, 'gamma': 0, 'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 300, 'objective': 'reg:linear', 'subsample': 0.7}


In [27]:
xgb_tune= xgb_grid.estimator

xgb_tune.fit(x_train,y_train)
xgb_tune.score(x_test,y_test)

0.8860465916025513

In [28]:
cvs = cross_val_score(xgb_tune,x_train,y_train,cv=10)
cvs , cvs.mean()

(array([0.98723741, 0.9821545 , 0.97920817, 0.98822994, 0.96081507,
        0.98620861, 0.97614513, 0.85294769, 0.9900092 , 0.89537911]),
 np.float64(0.9598334846987727))

In [29]:
xgb_grid.estimator

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [30]:
from xgboost import XGBRegressor
xgb_tune2 = XGBRegressor(
    base_score=0.5, booster='gbtree', colsample_bylevel=1,
    colsample_bynode=0.6, colsample_bytree=1, gamma=0,
    importance_type='gain', learning_rate=0.25, max_delta_step=0,
    max_depth=4, min_child_weight=1, n_estimators=400,
    n_jobs=1, objective='reg:squarederror',  # Fixed this!
    random_state=0, reg_alpha=0, reg_lambda=1,
    scale_pos_weight=1, subsample=1, verbosity=1
)

xgb_tune2.fit(x_train, y_train)
print("Training Score:", xgb_tune2.score(x_train, y_train))
print("Test Score:", xgb_tune2.score(x_test, y_test))


Training Score: 0.9997231848640362
Test Score: 0.8791956334785225


In [31]:
cvs = cross_val_score(xgb_tune2,x_train,y_train,cv=10)
cvs , cvs.mean()

(array([0.97353606, 0.97553886, 0.98622485, 0.98800811, 0.96746681,
        0.97599389, 0.92144943, 0.89829525, 0.99364276, 0.91731096]),
 np.float64(0.959746698961833))

In [32]:
np.sqrt(mean_squared_error(y_test,xgb_tune2.predict(x_test)))

np.float64(49.26778374814077)

# Test Model

In [33]:
list(X.columns)

['bath',
 'balcony',
 'total_sqft_int',
 'BHK',
 'price_per_sqft',
 'area_typeSuper built-up  Area ',
 'area_typeBuilt-up  Area',
 'area_typePlot  Area  ',
 'availability_Ready To move ',
 'locationWhitefield',
 'locationSarjapur  Road',
 'locationElectronic City',
 'locationMarathahalli',
 'locationRaja Rajeshwari Nagar',
 'locationHaralur Road',
 'locationHennur Road',
 'locationBannerghatta Road',
 'locationUttarahalli',
 'locationThanisandra',
 'locationElectronic City Phase II',
 'locationHebbal',
 'locationYelahanka',
 'location7th Phase JP Nagar',
 'locationKanakpura Road',
 'locationKR Puram',
 'locationSarjapur',
 'locationRajaji Nagar',
 'locationBellandur',
 'locationKasavanhalli',
 'locationBegur Road',
 'locationBanashankari',
 'locationKothanur',
 'locationHormavu',
 'locationHarlur',
 'locationAkshaya Nagar',
 'locationElectronics City Phase 1',
 'locationJakkur',
 'locationVarthur',
 'locationHSR Layout',
 'locationHennur',
 'locationRamamurthy Nagar',
 'locationChandap

In [34]:
#it help to get predict value of house by providing features value
def predict_house_price(model,bath,balcony,total_sqft_int,BHK,price_per_sqft,area_type,availability,location):
  x=np.zeros(len(X.columns))#create zero numpy array len=107 as input value for model
  #adding feature's value according to their column index
  x[0]=bath
  x[1]=balcony
  x[2]=total_sqft_int
  x[3]=BHK
  x[4]=price_per_sqft

  if'availability'=='Ready To Move':
    x[8]=1
  if 'area_type'+area_type in X.columns:
    area_type_index=np.where(X.columns=="area_type"+area_type[0][0])
    x[area_type_index]=1

    #print(area_type_index)
  if 'location_' +location in X.columns:
    loc_index=np.where(X.columns=='location_'+location[0][0])
    x[loc_index]=1

    #print(loc_index)
  #print(x)

  #feature scaling
  x=sc.transform([X][0])
  #print(x)
  return model.predict([X][0])
    



In [35]:
predict_house_price(model=xgb_tune2, bath=3,balcony=2,total_sqft_int=1672,BHK=3,price_per_sqft=8971.291866,area_type="Plot  Area",availability="Ready To Move",location="Devarabeesana Halli")

array([3083.7898, 3083.7898, 3083.7898, ..., 3046.8032, 3046.8032,
       3046.8032], dtype=float32)

# save model & laod model 

In [36]:
import joblib
# save model 
joblib.dump(xgb_tune2,'Bangalore_House_Prediction_Dataclean.pkl')

['Bangalore_House_Prediction_Dataclean.pkl']

In [37]:
joblib.dump(rfr, 'Bangalore_House_Prediction_Dataclean.pkl')

['Bangalore_House_Prediction_Dataclean.pkl']

In [38]:
# load model 
bangalore_house_price_prediction_model = joblib.load("Bangalore_House_Prediction_Dataclean.pkl")

In [39]:
#predict house price
predict_house_price(bangalore_house_price_prediction_model,bath=3,balcony=3,total_sqft_int=150,BHK=3,price_per_sqft=8514.285714,area_type="Built-up Area",availability="Ready To Move",location="Devarabeesana Halli")


/Users/ankushchoudhari76/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(


array([2335.4, 2335.4, 2335.4, ..., 2288.9, 2288.9, 2286.4])

In [40]:
#Import Libraries
import numpy as np
import pandas as pd
import joblib
 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
 
#load data
df = pd.read_csv("ohe_data_reduce_cat_class.csv")
 
# Split data
X= df.drop('price', axis=1)
y= df['price']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=51)
 
# feature scaling
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)
 
 
###### Load Model
 
model = joblib.load('Bangalore_House_Prediction_Dataclean.pkl')
 
 
# it help to get predicted value of house  by providing features value 
def predict_house_price(bath,balcony,total_sqft_int,bhk,price_per_sqft,area_type,availability,location):
 
  x =np.zeros(len(X.columns)) # create zero numpy array, len = 107 as input value for model
 
  # adding feature's value accorind to their column index
  x[0]=bath
  x[1]=balcony
  x[2]=total_sqft_int
  x[3]=bhk
  x[4]=price_per_sqft
 
  if "availability"=="Ready To Move":
    x[8]=1
 
  if 'area_type'+area_type in X.columns:
    area_type_index = np.where(X.columns=="area_type"+area_type)[0][0]
    x[area_type_index] =1
 
  if 'location_'+location in X.columns:
    loc_index = np.where(X.columns=="location_"+location)[0][0]
    x[loc_index] =1
 
  # feature scaling
  x = sc.transform([x])[0] # give 2d np array for feature scaling and get 1d scaled np array
 
  return model.predict([x])[0] # return the predicted value by train XGBoost model


In [43]:
#Import Libraries
from flask import Flask, request, render_template
 
import model # load model.py
 
app = Flask(__name__)
 
# render htmp page
@app.route('/')
def home():
    return render_template('index.html')
 
# get user input and the predict the output and return to user
@app.route('/predict',methods=['POST'])
def predict():
     
    #take data from form and store in each feature    
    input_features = [x for x in request.form.values()]
    bath = input_features[0]
    balcony = input_features[1]
    total_sqft_int = input_features[2]
    bhk = input_features[3]
    price_per_sqft = input_features[4]
    area_type = input_features[5]
    availability = input_features[6]
    location = input_features[7]
     
    # predict the price of house by calling model.py
    predicted_price = model.predict_house_price(bath,balcony,total_sqft_int,bhk,price_per_sqft,area_type,availability,location)       
 
 
    # render the html page and show the output
    return render_template('index.html', prediction_text='Predicted Price of Bangalore House is {}'.format(predicted_price))
 
# if __name__ == "__main__":
#     app.run(host="0.0.0.0", port="8080")
     
if __name__ == "__main__":
    app.run()


 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [06/Mar/2025 13:29:33] "GET / HTTP/1.1" 200 -
/Users/ankushchoudhari76/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
127.0.0.1 - - [06/Mar/2025 13:30:08] "POST /predict HTTP/1.1" 200 -
